import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from './components/sidebar.js'
import Notification from './components/notification.js'
import './styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <div>Hello</div> */}
      <body className={inter.className}>
        <Notification/>
        <SideBar />
        {children}
      
      </body>
    </html>
  )
}
